### ISSUE TITLE
Improve Acrylic blur, icon is not good with 1366x768 display

### ISSUE THREAD

**Issue by HuyHung1408** [krlvm/MediaFlyout#1]
![image](https://user-images.githubusercontent.com/86362423/146671287-a4ea1b27-8edd-48bd-b3e0-72a1f838072b.png)

Can you make it more consistent with the other part of the system?
![image](https://user-images.githubusercontent.com/86362423/146671297-65c3d10b-2645-4903-8225-70dbba4cbfed.png)

**Comment by krlvm** [comment]
Hello,

Unfortunately, the API that allows to enable acrylic in Win32 apps is undocumented and does not support such important options, as luminosity, in addition to that, it slows down window movement - so it is not possible fully copy standard flyouts behaviour and look.

Thanks for reporting this (because I'm on 125% scaling), I fixed the ugly icon bug in [version 1.0.7](https://github.com/krlvm/MediaFlyout/releases/tag/v1.0.7).

If you find acrylic better that the current effect (this effect is used by input language flyout), since v1.0.7 you can create a DWORD key `HCKU\SOFTWARE\krlvm\MediaFlyout\EnableFluentAcrylic`, set its value to `1` and restart the application.

**Comment by HuyHung1408** [comment]
Thanks a lot for your respond!

**Comment by krlvm** [comment]
MediaFlyout supports proper acrylic effect since [version 1.1](https://github.com/krlvm/MediaFlyout/releases/tag/v1.1)

**Comment by HuyHung1408** [comment]
Thanks a lot!
